# Generated by Django 6.0.5 on 2026-05-25 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AirportCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="IATA Airport Code (e.g. JFK, LHR)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmissionFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="e.g. Fuel, Electricity, Flights, Hotels, Ground Transport",
                        max_length=100,
                    ),
                ),
                (
                    "subcategory",
                    models.CharField(
                        help_text="e.g. Diesel, Natural Gas, Short-haul Business, Hotel-DE",
                        max_length=100,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=6, help_text="Factor rate", max_digits=12
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="Emission factor unit denominator (e.g. kg CO2e/L, kg CO2e/pkm, kg CO2e/room-night)",
                        max_length=50,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        default="GLOBAL",
                        help_text="Target geographic region (e.g. DE, US, IN, GLOBAL)",
                        max_length=100,
                    ),
                ),
                ("year", models.IntegerField(default=2026)),
                (
                    "source_reference",
                    models.CharField(
                        blank=True,
                        help_text="e.g. GHG Protocol, EPA 2026, DEFRA 2026",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "unique_together": {("category", "subcategory", "location", "year")},
            },
        ),
        migrations.CreateModel(
            name="IngestionSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive ingestion process label", max_length=255
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("SAP", "SAP ERP (Fuel & Procurement)"),
                            ("UTILITY", "Utility Portal (Electricity)"),
                            (
                                "TRAVEL",
                                "Corporate Travel API/CSV (Flights, Hotels, Ground)",
                            ),
                        ],
                        max_length=15,
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Processing"),
                            ("PROCESSED", "Processed"),
                            ("FAILED", "Failed Ingestion"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "raw_payload",
                    models.TextField(
                        blank=True,
                        help_text="Original raw text / API JSON file content",
                        null=True,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingestion_sources",
                        to="esg_app.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NormalizedRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.IntegerField(
                        choices=[(1, "Scope 1"), (2, "Scope 2"), (3, "Scope 3")]
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="e.g. Fuel, Electricity, Flights, Hotels, Ground Transport",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "activity_value",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Quantity in standardized units",
                        max_digits=15,
                    ),
                ),
                (
                    "activity_unit",
                    models.CharField(
                        help_text="Standardized unit (e.g. L, kWh, pkm, room-night)",
                        max_length=50,
                    ),
                ),
                (
                    "co2e_emissions_t",
                    models.DecimalField(
                        decimal_places=6, help_text="t CO2e calculated", max_digits=15
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Location code, facility or region name",
                        max_length=255,
                    ),
                ),
                (
                    "date_start",
                    models.DateField(help_text="Activity period start date"),
                ),
                ("date_end", models.DateField(help_text="Activity period end date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("FLAGGED", "Flagged (Suspicious)"),
                            ("APPROVED", "Approved (Auditable)"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                (
                    "flag_reason",
                    models.TextField(
                        blank=True,
                        help_text="Why the anomaly checker flagged this row",
                        null=True,
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Locks the record against modifications during audit periods",
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="normalized_records",
                        to="esg_app.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditTrail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("INGEST", "Ingested & Normalized"),
                            ("EDIT", "Data Overridden / Corrected"),
                            ("APPROVE", "Record Approved"),
                            ("REJECT", "Record Rejected"),
                            ("LOCK", "Reporting Period Locked"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "changed_fields",
                    models.JSONField(
                        blank=True,
                        help_text="Audit logs of edits: {'field': {'old': x, 'new': y}}",
                        null=True,
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        help_text="Auditable explanation for override, rejection, or sign-off"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "normalized_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_trails",
                        to="esg_app.normalizedrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RawRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSED", "Processed"),
                            ("FAILED", "Failed Validation"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        help_text="Stores the exact raw row fields as key-value pairs"
                    ),
                ),
                (
                    "validation_errors",
                    models.TextField(
                        blank=True,
                        help_text="JSON or text logs of validation anomalies",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_records",
                        to="esg_app.client",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_records",
                        to="esg_app.ingestionsource",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="normalizedrecord",
            name="raw_record",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="normalized",
                to="esg_app.rawrecord",
            ),
        ),
        migrations.CreateModel(
            name="LocationMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Plant code (WERKS) or facility ID", max_length=50
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable facility name", max_length=255
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        help_text="Country or Grid region code (e.g. DE, US-NE, IN)",
                        max_length=100,
                    ),
                ),
                (
                    "grid_emission_factor",
                    models.DecimalField(
                        decimal_places=6, help_text="kg CO2e / kWh", max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="esg_app.client",
                    ),
                ),
            ],
            options={
                "unique_together": {("client", "code")},
            },
        ),
    ]
