# Generated by Django 6.0.5 on 2026-05-25 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esg_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="normalizedrecord",
            name="raw_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="normalized_records",
                to="esg_app.rawrecord",
            ),
        ),
    ]
